services:
  posts-application:
    image: posts-application
    container_name: posts-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - project-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.41
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: posts
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"
    networks:
      - project-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  project-network:
volumes:
  mysql-volume: