spring.application.name=posts

spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://mysql_database:3306/posts
spring.datasource.username=admin
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

jwt.private.key=84281599c4c41eb2e51d60aaec079ab858aeecbefc876fb38c622a8b3672eda0
jwt.user.generator=AUTH-BACKEND
