server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: posts

jwt:
  private:
    key: 84281599c4c41eb2e51d60aaec079ab858aeecbefc876fb38c622a8b3672eda0
  user:
    generator: AUTH-BACKEND
